import { Quest, Blueprint, CraftingItem, SafeItem } from './types';

export const QUESTS: Quest[] = [
  { id: 1, name: "Picking Up The Pieces", objectives: ["Visit any area with a loot category icon", "Loot 3 containers"], locations: "Hydroponic Dome, Dam", rewards: ["1x Rattler III", "80x Medium Ammo"] },
  { id: 2, name: "Clearer Skies", objectives: ["Destroy 3 ARC enemies", "Get 3 ARC Alloy for Shani"], locations: "Dam Battlegrounds", rewards: ["3x Sterilized Bandage", "1x Light Shield", "Black Backpack Cosmetic"] },
  { id: 3, name: "Trash Into Treasure", objectives: ["Obtain 6 Wires", "Obtain 1 Battery"], locations: "Research Building, Dam", rewards: ["1x Tactical MK.1", "3x Adrenaline Shot"] },
  { id: 4, name: "Off The Radar", objectives: ["In one round: Visit a field depot", "Repair antenna on roof"], locations: "Field Depot (Any)", rewards: ["2x Defibrillator"] },
  { id: 5, name: "A Bad Feeling", objectives: ["Find and search any ARC Probe or ARC Courier"], locations: "Any Map", rewards: ["10x Metal Parts", "5x Steel Spring", "5x Duct Tape"] },
  { id: 6, name: "The Right Tool", objectives: ["Destroy a Fireball", "Destroy a Hornet", "Destroy a Turret"], locations: "Any Map", rewards: ["Cheer Emote", "1x Stitcher II", "1x Ext. Light Mag I"] },
  { id: 7, name: "Hatch Repairs", objectives: ["Repair leaking hydraulic pipes near Raider Hatch", "Search for hatch key near hatch"], locations: "Raider Hatch (Any)", rewards: ["1x Raider Hatch Key", "1x Binoculars"] },
  { id: 8, name: "Safe Passage", objectives: ["Destroy 2 ARC enemies using explosive grenade"], locations: "Research & Admin, Dam", rewards: ["5x Li'l Smoke Grenade", "3x Shrapnel Grenade", "3x Barricade Kit"] },
  { id: 9, name: "Down To Earth", objectives: ["In one round: Visit Field Depot", "Deliver Field Crate to Supply Station", "Collect reward"], locations: "Field Depot (Any)", rewards: ["1x Combat MK.1", "1x Medium Shield"] },
  { id: 10, name: "The Trifecta", objectives: ["Destroy Hornet", "Get Hornet Driver", "Destroy Snitch", "Get Snitch Scanner", "Destroy Wasp", "Get Wasp Driver"], locations: "Testing Annex, Dam", rewards: ["1x Dam Control Tower Key", "2x Defibrillator", "1x Raider Hatch Key"] },
  { id: 11, name: "A Better Use", objectives: ["Request Supply Drop from Call Station", "Loot a Supply Drop"], locations: "Supply Call Station (Any)", rewards: ["1x Ext. Light Mag I", "1x Stable Stock I", "1x Muzzle Brake II"] },
  { id: 12, name: "What Goes Around", objectives: ["Destroy any ARC enemy using a Fireball Burner"], locations: "Research & Admin, Dam", rewards: ["3x Blaze Grenade", "2x Noisemaker", "Cans Backpack"] },
  { id: 13, name: "Sparks Fly", objectives: ["Destroy Hornet with Trigger 'Nade or Snap Blast"], locations: "Any Map", rewards: ["1x Trigger Nade Blueprint", "4x Crude Explosives", "2x Processor"] },
  { id: 14, name: "Greasing Her Palms", objectives: ["Visit Locked Room in Water Treatment (Dam)", "Scope rocket thrusters (Spaceport)", "Visit barricaded area floor 6 Space Travel (Buried City)"], locations: "Various", rewards: ["1x Lure Grenade BP", "3x Speaker Component", "3x Electrical Components"] },
  { id: 15, name: "A First Foothold", objectives: ["Stabilize observation deck (Ridgeline)", "Enable comms (Olive Grove)", "Rotate satellite dishes", "Nail down roof plates"], locations: "Ridgeline, Blue Gate", rewards: ["3x Shrapnel Grenade", "3x Snap Blast", "3x Heavy Fuze"] },
  { id: 16, name: "Dormant Barons", objectives: ["Loot a Baron husk"], locations: "South Swamp Outpost", rewards: ["3x Door Blocker", "3x Li'l Smoke Grenade"] },
  { id: 17, name: "Mixed Signals", objectives: ["Destroy ARC Surveyor", "Obtain 1 Surveyor Vault"], locations: "Any Map", rewards: ["1x Photoelectric Cloak", "1x Raider Hatch Key"] },
  { id: 18, name: "What We Left Behind", objectives: ["Search 2 containers in Raider Camp", "Search South Swamp Outpost", "Search Bilguun's Hideout"], locations: "Various", rewards: ["1x Muzzle Brake II", "1x Vertical Grip II", "1x Stable Stock II"] },
  { id: 19, name: "Doctor's Orders", objectives: ["Obtain 2 Antiseptic", "Obtain 1 Syringe", "Obtain 1 Durable Cloth", "Obtain 1 Great Mullein"], locations: "Pharmacy, Buried City", rewards: ["3x Adrenaline Shot", "3x Sterilized Bandage", "1x Surge Shield Recharger"] },
  { id: 20, name: "Medical Merchandise", objectives: ["Search Departure Bldg exam rooms", "Search Hospital containers", "Search R&A medical room"], locations: "Various", rewards: ["1x Banana Charm", "3x Defibrillator", "2x Vita Shot"] },
  { id: 21, name: "A Reveal in Ruins", objectives: ["Search for ESR Analyzer in pharmacy", "Deliver to Lance"], locations: "Pharmacy, Buried City", rewards: ["1x Tactical Mk. 3 (Healing)", "1x Surge Shield Recharger"] },
  { id: 22, name: "Broken Monument", objectives: ["Reach Scrap Yard", "Search for compass", "Search for video tape", "Search for field rations", "Deliver items to Tian Wen"], locations: "Scrapyard, Dam", rewards: ["1x Arpeggio I", "1x Compensator II", "80x Medium Ammo"] },
  { id: 23, name: "Marked for Death", objectives: ["Reach Su Durante Warehouses in Outskirts"], locations: "Buried City", rewards: ["1x Shotgun Choke II", "1x Angled Grip II"] },
  { id: 24, name: "Straight Record", objectives: ["Reach Victory Ridge", "Disable power switches (3)", "Shutdown EMP trap"], locations: "Victory Ridge, Dam", rewards: ["5x Medium Gun Parts", "3x Adv. Mech Components"] },
  { id: 25, name: "A Lay of the Land", objectives: ["Reach Jiangsu Warehouse", "Find shipping notes", "Locate scanners in Control Tower A6", "Deliver LiDAR to Shani"], locations: "Jiangsu Warehouse, Spaceport", rewards: ["1x Dam Testing Key", "3x Zipline", "2x Smoke Grenade"] },
  { id: 26, name: "Market Correction", objectives: ["Locate cache near Marano Station"], locations: "Marano Station, Buried City", rewards: ["1x Silencer II", "1x Ext. Light Mag I", "1x Compensator I"] },
  { id: 27, name: "Keeping the Memory", objectives: ["Reach wreckage in Formical Hills"], locations: "Formical Hills, Dam", rewards: ["5x Simple Gun Parts", "5x Duct Tape", "5x Magnet"] },
  { id: 28, name: "Reduced to Rubble", objectives: ["Photo Collapsed Highway", "Go to Broken Earth", "Investigate unknown ARC machines"], locations: "Highway Collapse, Blue Gate", rewards: ["1x Zipline", "3x Barricade Kit", "3x Doorblockers"] },
  { id: 29, name: "With a Trace", objectives: ["Reach Barren Clearing", "Find signs of who brought down machines"], locations: "Barren Clearing, Blue Gate", rewards: ["1x Medium Shield"] },
  { id: 30, name: "Eyes on the Prize", objectives: ["Find roof terrace south-west of Southern Station", "Rewire solar panel using 3 Wires"], locations: "Old Town, Buried City", rewards: ["1x Ext. Shotgun Mag II", "1x Ext. Medium Mag II"] },
  { id: 31, name: "Battle Plans", objectives: ["Reach Victory Ridge", "Retrieve battle plans", "Deliver Aiva's Patch"], locations: "Victory Ridge, Dam", rewards: ["6x Crude Explosives", "2x Processor", "1x Music Box"] },
  { id: 32, name: "Industrial Espionage", objectives: ["Find Tian Wen's weapon cache", "Deliver Burletta"], locations: "Industrial Zone, Buried City", rewards: ["3x Mechanical Components", "3x Simple Gun Parts"] },
  { id: 33, name: "Unexpected Initiative", objectives: ["Reach Grandioso Apts", "Search for Fertilizer", "Search for Water Pump at Piazza Roma", "Deliver items"], locations: "Industrial, Buried City", rewards: ["1x IL Toro I", "1x Shotgun Choke II"] },
  { id: 34, name: "A Symbol of Unification", objectives: ["Reach Formicai Outpost", "Locate flag", "Hoist flag overlooking red lake"], locations: "Formicai Outpost, Dam", rewards: ["3x Mod Components", "5x Duct Tape"] },
  { id: 35, name: "Celeste's Journals", objectives: ["Retrieve journals from South Swamp", "Retrieve journals from northern outpost", "Deliver to Celeste"], locations: "South Swamp, Dam", rewards: ["1x Magnetic Accelerator", "3x Heavy Gun Parts", "1x Exodus Modules"] },
  { id: 36, name: "Back on Top", objectives: ["Mark Pattern House", "Mark white lookout tower", "Mark South Trench Tower", "Mark mural building"], locations: "Various", rewards: ["1x Renegade I", "1x Stable Stock III", "80x Medium Ammo"] },
  { id: 37, name: "The Major's Footlocker", objectives: ["Search for Aiva's mementos in apartments", "Deliver to Tian Wen"], locations: "Ruby Residences, Dam", rewards: ["1x Hullcracker Blueprint"] },
  { id: 38, name: "Out of the Shadows", objectives: ["Destroy a Rocketeer", "Obtain a Rocketeer Driver"], locations: "Testing Annex, Dam", rewards: ["3x Surge Shield Recharger", "2x Wolfpack"] },
  { id: 39, name: "Eyes in the Sky", objectives: ["Install LiDAR at Control Tower (Dam)", "Install LiDAR at Comm Tower (Spaceport)", "Install LiDAR on Galleria sign (Buried City)"], locations: "Various", rewards: ["1x Vita Spray", "5x Yellow Light Stick"] },
  { id: 40, name: "Our Presence Up There", objectives: ["Visit Pattern House", "Interact with Power Switch", "Complete antenna installation"], locations: "Pattern House, Dam", rewards: ["1x Buried City Town Hall Key", "1x Raider Hatch Key", "1x Jolt Mine"] },
  { id: 41, name: "Communication Hideout", objectives: ["Reach Red Tower", "Find missing battery", "Install and boot antenna"], locations: "Old Town, Buried City", rewards: ["1x Anvil III", "40x Heavy Ammo"] },
  { id: 42, name: "After Rain Comes", objectives: ["Find flooded solar panels", "Repair using 5 Wires and 2 Batteries"], locations: "Grandioso Apts, Buried City", rewards: ["5x Blue Light Stick", "3x Antiseptic", "5x Durable Cloth"] },
  { id: 43, name: "A Balanced Harvest", objectives: ["Go to Research Building", "Locate Lab 1"], locations: "Research Building, Dam", rewards: ["3x Adv. Mech Components", "3x Medium Gun Parts", "10x Steel Spring"] },
  { id: 44, name: "Untended Garden", objectives: ["Go to Hydroponic Dome", "Access data archive", "Upload data to terminal"], locations: "Hydroponic Dome, Dam", rewards: ["3x Adv. Mech Components", "3x Heavy Gun Parts", "5x Canister"] },
  { id: 45, name: "The Root of the Matter", objectives: ["Go to Research Building", "Search for seed vault", "Deliver Experimental Seed"], locations: "Research Building, Buried City", rewards: ["3x Adv. Mech Components", "3x Heavy Gun Parts", "3x Canister"] },
  { id: 46, name: "Water Troubles", objectives: ["Locate Flood Access Tunnel", "Find intake to Water Supply", "Sample water"], locations: "Red Lake Berm, Dam", rewards: ["3x Mechanical Components", "3x Simple Gun Parts", "3x Steel Spring"] },
  { id: 47, name: "Into the Fray", objectives: ["Destroy a Leaper", "Obtain Leaper Pulse Unit"], locations: "Research Building, Dam", rewards: ["1 Radio Renegade", "1 Burgerboy", "1 Vulcano III"] },
  { id: 48, name: "Source of Contamination", objectives: ["Reach Water Treatment", "Search Flood Spill Intake", "Investigate suspicious objects"], locations: "Water Treatment, Dam", rewards: ["5x Steel Spring", "5x Duct Tape", "1x Mod Components"] },
  { id: 49, name: "Switching the Supply", objectives: ["Find tunnels under Spaceport", "Find and turn valve"], locations: "Launch Towers, Spaceport", rewards: ["3x Synthesized Fuel"] },
  { id: 50, name: "A Warm Place to Rest", objectives: ["Locate Abandoned Highway Camp", "Search for survivors", "Follow markers", "Inspect grave"], locations: "Abandoned Highway, Buried City", rewards: ["3x Noisemaker", "5x Blue Light Stick"] },
  { id: 51, name: "Prescriptions of the Past", objectives: ["Visit Departure Building", "Find Medical Exam Room", "Search for records"], locations: "Departure Bldg, Spaceport", rewards: ["1x Heavy Shield", "1x Tactical Mk. 3 (Healing)"] },
  { id: 52, name: "Power Out", objectives: ["Find Electrical Substation", "Find missing engineer", "Carry fuse to Substation", "Enable power"], locations: "Electrical Substation, Spaceport", rewards: ["5x Wires", "5x Explosive Compound", "5x Oil"] },
  { id: 53, name: "Flickering Threat", objectives: ["Find Generator Room", "Repair Generator", "Find Ventilation Shaft", "Enable power"], locations: "North Complex Elevator, Dam", rewards: ["5x Medium Gun Parts", "3x Adv. Mech Components"] },
  { id: 54, name: "Bees!", objectives: ["Reach Olive Grove", "Search for bee hives"], locations: "Olive Grove, Blue Gate", rewards: ["1x Adv. Electrical Components", "3x Sensors"] },
  { id: 55, name: "Espresso", objectives: ["Find espresso machine", "Get parts for Apollo"], locations: "Plaza Rosa, Buried City", rewards: ["1x Coffee Pot", "3x Adrenaline Shot"] },
  { id: 56, name: "Life of a Pharmacist", objectives: ["Find Arbusto Farmacia", "Document hobbies, family, taste, skills"], locations: "Pharmacy, Buried City", rewards: ["1x Defibrillator", "1x Surge Shield Recharger", "3x Sterilized Bandage"] },
  { id: 57, name: "Tribute to Toledo", objectives: ["Get a Power Rod for Celeste"], locations: "Various", rewards: ["5x Magnet", "2x Adv. Mech Components", "3x Synthesized Fuel"] },
  { id: 58, name: "Digging Up Dirt", objectives: ["Locate Santa Maria Houses", "Locate Dead Drop"], locations: "Old Town, Buried City", rewards: ["2x Adv. Electrical Components", "4x Speaker Component"] },
  { id: 59, name: "Turnabout", objectives: ["Go to North Trench Tower", "Upload blackmail files"], locations: "North Trench Tower, Spaceport", rewards: ["2x Heavy Gun Parts", "2x Medium Gun Parts"] },
  { id: 60, name: "Building a Library", objectives: ["Locate Library", "Find romance, detective, and adventure books", "Deliver to Apollo"], locations: "Library, Buried City", rewards: ["1x Jolt Mine", "1x Heavy Fuze Grenade"] },
  { id: 61, name: "A New Type of Plant", objectives: ["Search for plant near Baron Husk", "Deliver to Lance"], locations: "Baron Husk, Dam", rewards: ["1x Vita Shot", "5x Antiseptic"] },
  { id: 62, name: "Armored Transports", objectives: ["Reach Checkpoint", "Search Guard huts for Key Card", "Reach Traffic Tunnel", "Unlock patrol car"], locations: "Headhouse, Blue Gate", rewards: ["3x Smoke Grenade", "3x Defibrillator"] },
  { id: 63, name: "Lost in Transmission", objectives: ["In one round: Visit Control Tower A6", "Reach top of tower"], locations: "Control Tower A6, Spaceport", rewards: ["1x Snap Hook"] }
];

export const BLUEPRINTS: Blueprint[] = [
  { name: "Anvil", workshop: "Gunsmith 2", recipe: "5x Mech Comp, 5x Simple Gun Parts", lootable: true, harvesterEvent: false, questReward: false, trailsReward: true },
  { name: "Anvil Splitter", workshop: "Gunsmith 3", recipe: "?", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Angled Grip II", workshop: "Gunsmith 2", recipe: "2x Mech Comp, 3x Duct Tape", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Barricade Kit", workshop: "Utility Station 2", recipe: "1x Mech Comp", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Bettina", workshop: "Gunsmith 3", recipe: "3x Adv Mech Comp, 3x Heavy Gun Parts, 3x Canister", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Blaze Grenade", workshop: "Explosives Station 3", recipe: "1x Expl Compound, 2x Oil", lootable: true, harvesterEvent: false, questReward: false, trailsReward: true },
  { name: "Bobcat", workshop: "Gunsmith 3", recipe: "?", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Burletta", workshop: "Gunsmith 1", recipe: "3x Mech Comp, 3x Simple Gun Parts", lootable: false, harvesterEvent: false, questReward: true, trailsReward: false },
  { name: "Combat Mk. 3 (AGGRESSIVE)", workshop: "Gear Bench 3", recipe: "2x Adv Elec Comp, 3x Processor", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Compensator II", workshop: "Gunsmith 2", recipe: "2x Mech Comp, 4x Wires", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Complex Gun Parts", workshop: "Refiner 3", recipe: "1x Light/Medium/Heavy Gun Parts", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Defibrillator", workshop: "Medical Lab 2", recipe: "9x Plastic Parts, 1x Moss", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Explosive Mine", workshop: "Explosives Station 3", recipe: "1x Expl Compound, 1x Sensors", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Extended Light Magazine II", workshop: "Gunsmith 2", recipe: "2x Mech Comp, 3x Steel Spring", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Equalizer", workshop: "Gunsmith 3", recipe: "3x Mag Accel, 3x Complex GP, 1x Queen Reactor", lootable: false, harvesterEvent: true, questReward: false, trailsReward: false },
  { name: "Heavy Gun Parts", workshop: "Refiner 2", recipe: "4x Simple Gun Parts", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Horizontal Grip", workshop: "Gunsmith 3", recipe: "2x Mod Comp, 5x Duct Tape", lootable: true, harvesterEvent: false, questReward: false, trailsReward: true },
  { name: "Hullcracker", workshop: "Gunsmith 3", recipe: "1x Mag Accel, 3x Heavy GP, 1x Exodus Mod", lootable: false, harvesterEvent: false, questReward: true, trailsReward: false },
  { name: "Il Toro", workshop: "Gunsmith 1", recipe: "5x Mech Comp, 6x Simple GP", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Jolt Mine", workshop: "Explosives Station 2", recipe: "1x Elec Comp, 1x Battery", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Jupiter", workshop: "Gunsmith 3", recipe: "3x Mag Accel, 3x Complex GP, 1x Queen Reactor", lootable: false, harvesterEvent: true, questReward: false, trailsReward: false },
  { name: "Launcher Ammo", workshop: "Workbench 1", recipe: "5x Metal Parts, 1x Crude Explosives", lootable: false, harvesterEvent: false, questReward: true, trailsReward: false },
  { name: "Light Gun Parts", workshop: "Refiner 2", recipe: "4x Simple Gun Parts", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Light Stick (Any)", workshop: "Utility Station 1", recipe: "3x Chemicals", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Looting Mk. 3 (SURVIVOR)", workshop: "Gear Bench 3", recipe: "2x Adv Elec Comp, 3x Processor", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Lure Grenade", workshop: "Utility Station 2", recipe: "1x Speaker Comp, 1x Elec Comp", lootable: false, harvesterEvent: false, questReward: true, trailsReward: false },
  { name: "Muzzle Brake II", workshop: "Gunsmith 2", recipe: "2x Mech Comp, 4x Wires", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Osprey", workshop: "Gunsmith 3", recipe: "2x Adv Mech Comp, 3x Medium GP, 7x Wires", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Padded Stock", workshop: "Gunsmith 3", recipe: "2x Mod Comp, 5x Duct Tape", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Remote Raider Flare", workshop: "Utility Station 1", recipe: "2x Chemicals, 4x Rubber Parts", lootable: true, harvesterEvent: false, questReward: false, trailsReward: true },
  { name: "Shotgun Choke II", workshop: "Gunsmith 2", recipe: "2x Mech Comp, 4x Wires", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Smoke Grenade", workshop: "Utility Station 2", recipe: "14x Chemicals, 1x Canister", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Stable Stock II", workshop: "Gunsmith 2", recipe: "2x Mech Comp, 3x Duct Tape", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Tactical Mk. 3 (DEFENSE/HEAL)", workshop: "Gear Bench 3", recipe: "2x Adv Elec Comp, 3x Processor", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Tagging Grenade", workshop: "Utility Station 3", recipe: "1x Elec Comp, 1x Sensors", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Torrente", workshop: "Gunsmith 3", recipe: "2x Adv Mech Comp, 3x Medium GP, 6x Steel Spring", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Trigger 'Nade", workshop: "Explosives Station 2", recipe: "2x Crude Explosives, 1x Processor", lootable: true, harvesterEvent: false, questReward: true, trailsReward: false },
  { name: "Venator", workshop: "Gunsmith 2", recipe: "2x Adv Mech Comp, 3x Medium GP, 5x Magnet", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Vertical Grip II", workshop: "Gunsmith 2", recipe: "2x Mech Comp, 3x Duct Tape", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Vita Shot", workshop: "Medical Lab 3", recipe: "2x Antiseptic, 1x Syringe", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Vita Spray", workshop: "Medical Lab 3", recipe: "3x Antiseptic, 1x Canister", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Vulcano", workshop: "Gunsmith 3", recipe: "1x Mag Accel, 3x Heavy GP, 1x Exodus Mod", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
  { name: "Wolfpack", workshop: "Explosives Station 3", recipe: "2x Expl Compound, 2x Sensors", lootable: true, harvesterEvent: false, questReward: false, trailsReward: false },
];

export const CRAFTING_ITEMS: CraftingItem[] = [
  // Page 2
  { item: "Dog Collar", quantity: 1, neededFor: "Scrappy 2", location: "Residential" },
  { item: "Lemons", quantity: 3, neededFor: "Scrappy 3", location: "Nature" },
  { item: "Apricots", quantity: 3, neededFor: "Scrappy 3", location: "Nature" },
  { item: "Prickly Pears", quantity: 6, neededFor: "Scrappy 4", location: "Nature" },
  { item: "Olives", quantity: 6, neededFor: "Scrappy 4", location: "Nature" },
  { item: "Cat Bed", quantity: 1, neededFor: "Scrappy 4", location: "Residential/Commercial" },
  { item: "Mushrooms", quantity: 12, neededFor: "Scrappy 5", location: "Nature" },
  { item: "Apricots", quantity: 12, neededFor: "Scrappy 5", location: "Nature" },
  { item: "Very Comfortable Pillow", quantity: 3, neededFor: "Scrappy 5", location: "Residential/Commercial" },
  { item: "Metal Parts", quantity: 20, neededFor: "Gunsmith 1", location: "Basic Material" },
  { item: "Rubber Parts", quantity: 30, neededFor: "Gunsmith 1", location: "Basic Material" },
  { item: "Rusted Tools", quantity: 3, neededFor: "Gunsmith 2", location: "Mechanical" },
  { item: "Mechanical Components", quantity: 5, neededFor: "Gunsmith 2", location: "Mechanical/Refiner" },
  { item: "Wasp Driver", quantity: 8, neededFor: "Gunsmith 2", location: "Drones" },
  { item: "Rusted Gear", quantity: 3, neededFor: "Gunsmith 3", location: "Industrial" },
  { item: "Adv. Mechanical Components", quantity: 5, neededFor: "Gunsmith 3", location: "Mechanical/Refiner" },
  { item: "Sentinel Firing Core", quantity: 4, neededFor: "Gunsmith 3", location: "Drones" },
  { item: "Plastic Parts", quantity: 25, neededFor: "Gear Bench 1", location: "Basic Material" },
  { item: "Fabric", quantity: 30, neededFor: "Gear Bench 1", location: "Basic Material" },
  { item: "Power Cable", quantity: 3, neededFor: "Gear Bench 2", location: "Electrical/Resid./Comm." },
  { item: "Electrical Components", quantity: 5, neededFor: "Gear Bench 2", location: "Electrical/Refiner" },
  { item: "Wasp Driver", quantity: 5, neededFor: "Gear Bench 2", location: "Drones" },
  { item: "Industrial Battery", quantity: 3, neededFor: "Gear Bench 3", location: "Industrial" },
  { item: "Adv. Electrical Components", quantity: 5, neededFor: "Gear Bench 3", location: "Electrical/Refiner" },
  { item: "Bastion Cell", quantity: 6, neededFor: "Gear Bench 3", location: "Drones" },
  { item: "Fabric", quantity: 50, neededFor: "Medical Lab 1", location: "Basic Material" },
  { item: "ARC Alloy", quantity: 6, neededFor: "Medical Lab 1", location: "Drones" },
  { item: "Cracked Bioscanner", quantity: 2, neededFor: "Medical Lab 2", location: "Medical" },
  { item: "Durable Cloth", quantity: 5, neededFor: "Medical Lab 2", location: "Medical/Commercial" },
  { item: "Tick Pod", quantity: 8, neededFor: "Medical Lab 2", location: "Drones" },
  // Page 3
  { item: "Rusted Shut Medical Kit", quantity: 3, neededFor: "Medical Lab 3", location: "Medical" },
  { item: "Antiseptic", quantity: 8, neededFor: "Medical Lab 3", location: "Medical" },
  { item: "Surveyor Vault", quantity: 5, neededFor: "Medical Lab 3", location: "Drones" },
  { item: "Rubber Parts", quantity: 50, neededFor: "Explosives Bench 1", location: "Basic Material" },
  { item: "ARC Alloy", quantity: 6, neededFor: "Explosives Bench 1", location: "Drones" },
  { item: "Synthesized Fuel", quantity: 3, neededFor: "Explosives Bench 2", location: "Exodus/Celeste" },
  { item: "Crude Explosives", quantity: 5, neededFor: "Explosives Bench 2", location: "Industrial/Security/Refiner" },
  { item: "Pop Trigger", quantity: 5, neededFor: "Explosives Bench 2", location: "Drones" },
  { item: "Laboratory Reagents", quantity: 3, neededFor: "Explosives Bench 3", location: "Medical" },
  { item: "Explosive Compound", quantity: 5, neededFor: "Explosives Bench 3", location: "Industrial/Security/Refiner" },
  { item: "Rocketeer Driver", quantity: 3, neededFor: "Explosives Bench 3", location: "Drones" },
  { item: "Plastic Parts", quantity: 50, neededFor: "Utility Station 1", location: "Basic Material" },
  { item: "ARC Alloy", quantity: 6, neededFor: "Utility Station 1", location: "Drones" },
  { item: "Damaged Heat Sink", quantity: 2, neededFor: "Utility Station 2", location: "Technological" },
  { item: "Electrical Components", quantity: 5, neededFor: "Utility Station 2", location: "Electrical/Refiner" },
  { item: "Snitch Scanner", quantity: 6, neededFor: "Utility Station 2", location: "Drones" },
  { item: "Fried Motherboard", quantity: 3, neededFor: "Utility Station 3", location: "Technological" },
  { item: "Adv. Electrical Components", quantity: 5, neededFor: "Utility Station 3", location: "Electrical/Refiner" },
  { item: "Leaper Pulse Unit", quantity: 4, neededFor: "Utility Station 3", location: "Drones" },
  { item: "Metal Parts", quantity: 60, neededFor: "Refiner 1", location: "Basic Material" },
  { item: "ARC Powercell", quantity: 5, neededFor: "Refiner 1", location: "Drones" },
  { item: "Toaster", quantity: 3, neededFor: "Refiner 2", location: "Residential" },
  { item: "ARC Motion Core", quantity: 5, neededFor: "Refiner 2", location: "Drones (Probes)" },
  { item: "Fireball Burner", quantity: 8, neededFor: "Refiner 2", location: "Drones" },
  { item: "Motor", quantity: 3, neededFor: "Refiner 3", location: "Mechanical" },
  { item: "ARC Circuitry", quantity: 10, neededFor: "Refiner 3", location: "Drones (Probes)" },
  { item: "Bombardier Cell", quantity: 6, neededFor: "Refiner 3", location: "Drones" },
  // Page 7 (Quest specific)
  { item: "ARC Alloy", quantity: 3, neededFor: "Clearer Skies", location: "Drones" },
  { item: "Wires", quantity: 6, neededFor: "Trash Into Treasure", location: "Electrical/Tech/Celeste" },
  { item: "Battery", quantity: 1, neededFor: "Trash Into Treasure", location: "Tech/Electrical/Celeste" },
  { item: "Snitch Scanner", quantity: 2, neededFor: "The Trifecta", location: "Drones" },
  { item: "Wasp Driver", quantity: 2, neededFor: "The Trifecta", location: "Drones" },
  { item: "Hornet Driver", quantity: 2, neededFor: "The Trifecta", location: "Drones" },
  { item: "Surveyor Vault", quantity: 1, neededFor: "Mixed Signals", location: "Drones" },
  { item: "Water Pump", quantity: 1, neededFor: "Unexpected Initiative", location: "Mechanical/Industrial" },
  { item: "Rocketeer Driver", quantity: 1, neededFor: "Out of the Shadows", location: "Drones" },
  { item: "Antiseptic", quantity: 2, neededFor: "Doctor's Orders", location: "Medical" },
  { item: "Syringe", quantity: 1, neededFor: "Doctor's Orders", location: "Medical/Celeste" },
  { item: "Durable Cloth", quantity: 1, neededFor: "Doctor's Orders", location: "Medical/Comm" },
  { item: "Great Mullein", quantity: 1, neededFor: "Doctor's Orders", location: "Nature/Celeste" },
  { item: "ESR Analyzer", quantity: 1, neededFor: "A Reveal in Ruins", location: "Plaza Rosa Pharmacy" },
  // Page 8 (Parts)
  { item: "Metal Parts", quantity: 150, neededFor: "Part 1", location: "Basic Materials" },
  { item: "Rubber Parts", quantity: 200, neededFor: "Part 1", location: "Basic Materials" },
  { item: "ARC Alloy", quantity: 80, neededFor: "Part 1", location: "Drones" },
  { item: "Steel Spring", quantity: 15, neededFor: "Part 1", location: "Mechanical/Celeste" },
  { item: "Durable Cloth", quantity: 35, neededFor: "Part 2", location: "Medical/Commercial" },
  { item: "Wires", quantity: 30, neededFor: "Part 2", location: "Electrical/Tech/Celeste" },
  { item: "Electrical Components", quantity: 30, neededFor: "Part 2", location: "Electrical/Refiner" },
  { item: "Cooling Fans", quantity: 5, neededFor: "Part 2", location: "Technological" },
  { item: "Light Bulb", quantity: 5, neededFor: "Part 3", location: "Electrical" },
  { item: "Battery", quantity: 30, neededFor: "Part 3", location: "Tech/Electrical/Celeste" },
  { item: "Sensors", quantity: 20, neededFor: "Part 3", location: "Security/Tech/Celeste" },
  { item: "Exodus Modules", quantity: 1, neededFor: "Part 3", location: "Exodus/Celeste" },
  { item: "Humidifier", quantity: 5, neededFor: "Part 4", location: "Residential" },
  { item: "Adv. Electrical Components", quantity: 5, neededFor: "Part 4", location: "Electrical/Refiner" },
  { item: "Magnetic Accelerator", quantity: 3, neededFor: "Part 4", location: "Exodus" },
  { item: "Leaper Pulse Unit", quantity: 3, neededFor: "Part 4", location: "Drones" },
  { item: "Combat Items", quantity: "250k Value", neededFor: "Part 5", location: "Turn in items" },
  { item: "Survival Items", quantity: "100k Value", neededFor: "Part 5", location: "Turn in items" },
  { item: "Provisions", quantity: "180k Value", neededFor: "Part 5", location: "Turn in items" },
  { item: "Materials", quantity: "300k Value", neededFor: "Part 5", location: "Turn in items" },
];

export const SAFE_TO_RECYCLE: SafeItem[] = [
  { name: "Alarm Clock", category: "Recycle" },
  { name: "ARC Coolant", category: "Recycle" },
  { name: "ARC Flex Rubber", category: "Recycle" },
  { name: "ARC Performance Steel", category: "Recycle" },
  { name: "ARC Synthetic Resin", category: "Recycle" },
  { name: "ARC Thermo Lining", category: "Recycle" },
  { name: "Bicycle Pump", category: "Recycle" },
  { name: "Broken Flashlight", category: "Recycle" },
  { name: "Broken Guidance System", category: "Recycle" },
  { name: "Broken Handheld Radio", category: "Recycle" },
  { name: "Broken Taser", category: "Recycle" },
  { name: "Burned ARC Circuitry", category: "Recycle" },
  { name: "Burned Tick Pod", category: "Recycle" },
  { name: "Candle Holder", category: "Recycle" },
  { name: "Coolant", category: "Recycle" },
  { name: "Cooling Coil", category: "Recycle" },
  { name: "Crumpled Plastic Bottle", category: "Recycle" },
  { name: "Damaged ARC Motion Core", category: "Recycle" },
  { name: "Damaged ARC Powercell", category: "Recycle" },
  { name: "Damaged Fireball Burner", category: "Recycle" },
  { name: "Damaged Hornet Driver", category: "Recycle" },
  { name: "Damaged Rocketeer Driver", category: "Recycle" },
  { name: "Damaged Snitch Scanner", category: "Recycle" },
  { name: "Damaged Wasp Driver", category: "Recycle" },
  { name: "Deflated Football", category: "Recycle" },
  { name: "Degraded ARC Rubber", category: "Recycle" },
  { name: "Diving Goggles", category: "Recycle" },
  { name: "Dried-Out ARC Resin", category: "Recycle" },
  { name: "Expired Respirator", category: "Recycle" },
  { name: "Frying Pan", category: "Recycle" },
  { name: "Garlic Press", category: "Recycle" },
  { name: "Household Cleaner", category: "Recycle" },
  { name: "Ice Cream Scooper", category: "Recycle" },
  { name: "Impure ARC Coolant", category: "Recycle" },
  { name: "Industrial Charger", category: "Recycle" },
  { name: "Industrial Magnet", category: "Recycle" },
  { name: "Metal Brackets", category: "Recycle" },
  { name: "Number Plate", category: "Recycle" },
  { name: "Polluted Air Filter", category: "Recycle" },
  { name: "Power Bank", category: "Recycle" },
  { name: "Radio", category: "Recycle" },
  { name: "Remote Control", category: "Recycle" },
  { name: "Ripped Safety Vest", category: "Recycle" },
  { name: "Rocket Thruster", category: "Recycle" },
  { name: "Rubber Pad", category: "Recycle" },
  { name: "Ruined Accordion", category: "Recycle" },
  { name: "Ruined Augment", category: "Recycle" },
  { name: "Ruined Baton", category: "Recycle" },
  { name: "Ruined Handcuffs", category: "Recycle" },
  { name: "Ruined Parachute", category: "Recycle" },
  { name: "Ruined Tactical Vest", category: "Recycle" },
  { name: "Ruined Riot Shield", category: "Recycle" },
  { name: "Rusted Bolts", category: "Recycle" },
  { name: "Rusty ARC Steel", category: "Recycle" },
  { name: "Spring Cushion", category: "Recycle" },
  { name: "Spotter Relay", category: "Recycle" },
  { name: "Tattered ARC Lining", category: "Recycle" },
  { name: "Tattered Clothes", category: "Recycle" },
  { name: "Thermostat", category: "Recycle" },
  { name: "Torn Blanket", category: "Recycle" },
  { name: "Turbo Pump", category: "Recycle" },
  { name: "Unusable Weapon", category: "Recycle" },
  { name: "Water Filter", category: "Recycle" },
];

export const SAFE_TO_SELL: SafeItem[] = [
  { name: "Bloated Tuna Can", category: "Sell" },
  { name: "Blown Fuses", category: "Sell" },
  { name: "Breathtaking Snow Globe", category: "Sell" },
  { name: "Coffee Pot", category: "Sell" },
  { name: "Dart Board", category: "Sell" },
  { name: "Expired Pasta", category: "Sell" },
  { name: "Fine Wristwatch", category: "Sell" },
  { name: "Lance's Mixtape (5th Edition)", category: "Sell" },
  { name: "Music Album", category: "Sell" },
  { name: "Music Box", category: "Sell" },
  { name: "Painted Box", category: "Sell" },
  { name: "Playing Cards", category: "Sell" },
  { name: "Poster of Natural Wonders", category: "Sell" },
  { name: "Pottery", category: "Sell" },
  { name: "Red Coral Jewelry", category: "Sell" },
  { name: "Rosary", category: "Sell" },
  { name: "Silver Teaspoon Set", category: "Sell" },
  { name: "Statuette", category: "Sell" },
  { name: "Torn Book", category: "Sell" },
  { name: "Vase", category: "Sell" },
  { name: "Volcanic Rock", category: "Sell" },
];
